### ISSUE TITLE
stdlib processing fails

### ISSUE THREAD

**Issue by kylekyle** [docmeta/rubydoc.info#100]
The thread that process docs for standard libs fails on line 44 of lib/extensions.rb since generate_yardoc is called with the wrong number of arguments. It doesn't show up in the logs since Thread.abort_on_exception is false by default. 

I would submit a PR, but I'm not sure how to check if YARD is in safe mode (which is the missing parameter).

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
