### ISSUE TITLE
Suggestion: Gem Version Switch

### ISSUE THREAD

**Issue by tf** [docmeta/rubydoc.info#104]
Not really sure if this is the right place: But since docs are stored for different gem versions anyway, I think it would be really cool if there was some kind of switch to jump to a different version directly. That way it might also become more clear which version of the docs one is currently viewing.

**Comment by franklinyu** [comment]
Any update? Or at least, is it PR-welcome?

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. We have no plans to work on this but the short answer is yes, a PR would be welcome.
