### ISSUE TITLE
HTTPS on RubyDoc.info

### ISSUE THREAD

**Issue by michaelmior** [docmeta/rubydoc.info#105]
Nowadays it's quite easy to get free certificates. Would be nice if someone who has access has a bit of time to set this up.

**Comment by ivan-kolmychek** [comment]
Well, even if you don't want to set it up completely, the good first step can be to use something like CloudFlare to terminate the HTTPS. The free tier should allow that.

I'm not sure are there any limits on traffic tho; I'm using it as SSL termination means mostly for small stuff like blog on github pages. :)

**Comment by ChallahuAkbar** [comment]
Bumping this since it's been just under a year and nothing has happened with this. As has been mentioned, there's really no excuse not to be using https since it's so easy to set up!

**Comment by zapnap** [comment]
👍 Fair point. Took care of this today. SSL should be working now.

cc @lsegal
