### ISSUE TITLE
Implement Algolia DocSeach

### ISSUE THREAD

**Issue by manuelmeurer** [docmeta/rubydoc.info#106]
Hi there,

I'm the creator of RubyDocs (https://rubydocs.org/, https://github.com/krautcomputing/rubydocs). I recently found [DocSearch from Algolia](https://community.algolia.com/docsearch/) which seems to be a fantastic search tool. I contacted them to talk about a way to implement DocSearch on RubyDocs, but since RubyDocs uses [sdoc](https://github.com/voloko/sdoc) to generate the docs, a basic search is already built-in.
But maybe this would be interesting for Rubydoc.info? I'm thinking it would be great if I could search through the YARD docs of a specific version of a gem/project with DocSeach.
What do you think? :smile: 

Cheers,
Manuel

**Comment by lsegal** [comment]
I looked into this (contacted the team) but it doesn't seem like Algolia will be the right fit for rubydoc.info. It might be better to look into the search that sdoc provides and port that over to YARD-- that would likely be a better step, and something we could eventually index across projects on our side. We would totally be up for PRs that started to look at that!
