### ISSUE TITLE
Rubydoc with cookbook documentation

### ISSUE THREAD

**Issue by dasbiswajit** [docmeta/rubydoc.info#108]
He Team,
Just wondering is there any way to show documentation for chef cookbooks(recipies) for github projects. I know there is a plugin => https://github.com/rightscale/yard-chef. for this is there any way to incorporate rubydoc.info? Any help will be usefull.
Regards
Biswajit Das

**Comment by joerg** [comment]
Hi,

This is advertisement for my own project, but there is www.chefdoc.info at github.com/chefdoc which is more or less a fork of yard-chef in combination with a fork of rubydoc.info to achive exactly this.
I also could really need some help with the development, so if you have some spare time left... ;-)

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
