### ISSUE TITLE
Can't generate docs for jnicklas/capybara: Invalid git repository or URL

### ISSUE THREAD

**Issue by Ajedi32** [docmeta/rubydoc.info#110]
The docs for [jnicklas/capybara](https://github.com/jnicklas/capybara) seem to be [broken on `rubydoc.info`](http://www.rubydoc.info/github/jnicklas/capybara). Every time I try to generate them I get the error message "Invalid git repository or URL":

![screenshot-www rubydoc info 2016-07-05 10-51-12](https://cloud.githubusercontent.com/assets/1876931/16590749/68439d98-429e-11e6-9c88-8adf8b24f19e.png)

I can clone the repo just fine on my PC, so I'm uncertain as to why this is happening.

Possibly related: #31

**Comment by lsegal** [comment]
We did an upgrade on the site yesterday but it seemed to not have applied cleanly. 27107468c22ce25753d1f0d1b10db864bb19af4c and its respective deploy should have resolved this. Thanks for reporting!
