### ISSUE TITLE
Sidebar does not load

### ISSUE THREAD

**Issue by handicraftsman** [docmeta/rubydoc.info#112]
Server basically does not answer. Samples:

[Cinch](http://www.rubydoc.info/search/gems/cinch?q=message)
[Gtk3](http://www.rubydoc.info/gems/gtk3/3.1.0)

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
