### ISSUE TITLE
Internal links go to wrong gem version

### ISSUE THREAD

**Issue by MaxPleaner** [docmeta/rubydoc.info#113]
I just entered pushed a new gem version with updated YARD docs. 

When I click the "documentation" button on my gem's page it goes to the right version. But when I click the "Top Level Namespace", the link that opens is from the previous gem version. From that point on, any links I click will be for the older gem version.

If I manually enter `/0.0.3/` in the url (in this case, the newest version) then all the links go to the right gem version.

But something seems to happen behind the scenes when I click links. The URL doesn't say the gem version, but it switches to the older one.

If you want to see an example, you can check out http://www.rubydoc.info/gems/gemmyrb/

Thanks

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
