### ISSUE TITLE
Percentage character (%) not showing up in sourcre

### ISSUE THREAD

**Issue by MaxPleaner** [docmeta/rubydoc.info#118]
I have a source method like this, it's documented using yard:

```rb
    # Calls given method_name on other_node, passing the opposite direction
    # to the one given as an argument. This keeps :next and :prev in sync.
    # @param direction [Symbol]
    #   something should have already been added/removed here
    # @param other_node [Node] the node which was added/removed
    # @param method_name [Symbol] the method to invoke on other_node
    # @return [void]
    def update_opposite_direction(direction, other_node, method_name, *other_args)
      other_direction = (%i{next prev} - [direction])[0]
      other_node.send(method_name, other_direction, self, *other_args, false)
    end
```

The issue is that `%i{next prev}` does not show up correctly on Rubydoc:

![err1](https://user-images.githubusercontent.com/5035719/31737057-364684ac-b3fb-11e7-8d51-29d8133ca0ce.PNG)

The `%` on line 158 is missing.

What's weird is that I only see this issue when I open the page for the class which contains this method: ([link](http://www.rubydoc.info/gems/markov_twitter/MarkovTwitter/MarkovBuilder/Node#update_opposite_direction-instance_method)). If I open the permalink page I don't see it and everything looks fine ([link](http://www.rubydoc.info/gems/markov_twitter/MarkovTwitter%2FMarkovBuilder%2FNode:update_opposite_direction)).

**Comment by shevegen** [comment]
Odd. Perhaps there is some hardcoded entry for the symbol-style? I think %i is not that long part of main ruby, but I may be wrong here. What I could naively assume is that there is perhaps some hardcoded table that allows only certain % variants - but I am just totally guessing into the dark here, I am very likely completely wrong.

**Comment by maxp-edcast** [comment]
I just checked again and I don't see the issue. Have no idea what happened there.

**Comment by lsegal** [comment]
This is likely due to a parsing bug from previous versions of YARD. Thanks for reporting!
