### ISSUE TITLE
documentation is not generated after version bump for *one* module

### ISSUE THREAD

**Issue by Nondv** [docmeta/rubydoc.info#120]
Hi!

My gem's last release was under version 1.2.0.
In [readme](http://www.rubydoc.info/gems/ruby-mpd-client/file/README.md) you can see proper version in breadcrumbs (on the top).

But if you navigate in `MPD::Commands` ([link](http://www.rubydoc.info/gems/ruby-mpd-client/MPD/Commands)) module version will changed to 1.1.0.

It seems that all classes were generated properly except this module.
Code contains `@!macro` and `@!parse` but locally documentation is being generated just fine (yard 0.9.12).

**Comment by lsegal** [comment]
This looks like a caching issue. Sorry for the delayed response, but it looks resolved now. Please re-open or file a support ticket at https://rubydoc.tenderapp.com if this persists.
