### ISSUE TITLE
sharing  .yardopts

### ISSUE THREAD

**Issue by noraj** [docmeta/rubydoc.info#121]
The `.yardopts` used by rubydoc.info is not provided on this repository (I don't know if it's wanted or not).

The request is simple, can you share the `.yardopts`?

This will allow me and other users to use the same options as rubydoc.info in order to have the same behaviour of rendering in local and on rubydoc.info.

**Comment by lsegal** [comment]
rubydoc.info doesn't have a .yardopts file. Options are entirely dictated by the .yardopts file in each project or gem.

Can you explain a little bit more about what you are looking for?

**Comment by noraj1337** [comment]
I wasn't having the same render behaviour when locally rendering with `yard doc && yard server` and on rubydoc.info so I was supposing that rubydoc.info was using some special config I didn't know about.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
