### ISSUE TITLE
Documentation unavailable or mixed up between versions

### ISSUE THREAD

**Issue by noraj1337** [docmeta/rubydoc.info#122]
Here is the comment I left here (https://github.com/lsegal/yard/issues/1146) yesterday.

> I released a gem (a pre-release version), it was the first version on rubygems, the documentation was available during the 10 minutes following my publishing. I went to eat. I went back 1 hour later and a colleague told me the doc was unavailable, I checked and the doc was dead except the README.md.

Plus rubygems.org was not seing 0.0.1.rc2 as a new version compared to 0.0.1.rc1 so I pushed a 0.0.2.pre just to see if rubydoc.info will build a new doc version or not. Now the doc is alive but that is still the documentation of the 0.0.1.rc1. In fact it's mixed up.

When going to http://www.rubydoc.info/gems/nvd_feed_api/ I see the 0.0.1.rc2 / 0.0.2.pre README but when going to http://www.rubydoc.info/gems/nvd_feed_api/file/README.md I still see the 0.0.1.rc1 README. Even when another brower, cleaning the cache and all...

As you can see in the Breadcrumb, all pages in `Classes` + `Methods` + the homepage are from 0.0.2.pre : 
![](https://i.imgur.com/Bf8GlIq.png)

And all files in  `Files` are from 0.0.1.rc1 : 
![](https://i.imgur.com/gWoXaK1.png)

That's explaining why additional files from 0.0.1.rc1 are not displayed because all files in `Files` section are from 0.0.1.rc1.

I don't understand what's going on at all.

**Comment by noraj1337** [comment]
Update : new it's even better : 

![](https://i.imgur.com/W0qFBgv.png)

```
Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:

XID: 96338603

Varnish cache server
```

**Comment by lsegal** [comment]
Rubydoc.info doesn't have support for pre-release gem versions. The general expectation is that they will not be displayed. To be honest, I'm surprised that the 0.0.1.rc1 managed to show up-- it shouldn't be there.

Once you release a non-rc or non-pre version, it should display on rubydoc.info.

**Comment by noraj1337** [comment]
Thanks for the info.

**Comment by noraj1337** [comment]
@lsegal It could be great to write this somewhere.
