### ISSUE TITLE
Small display info (version mismatch) - probably only a cosmetic "issue" but I will report it anyway

### ISSUE THREAD

**Issue by ghost** [docmeta/rubydoc.info#123]
First, an image:

https://i.imgur.com/2JAnL7U.png

Not sure if this image will be available for a long time so I describe the situation.

I just uploaded a new gem.

(a) The URL shows: 

www.rubydoc.info/gems/rbt/0.3.3

(b) however had, the popup window in the middle says: "Processing rbt" then new line and "rbt (0.3.2) is being processed". This is confusing because the URL says 0.3.3 so it should say 0.3.3 shouldn't it?

Link on top left says Libraries > rbt (0.3.2)

I think this may happen because I uploaded 0.3.2 too, a bit before, but did not generate the documentation yet, so perhaps this is why it picked not the most recent version, not sure. Either way it is a bit confusing if the URL says 0.3.3, to then see 0.3.2 is being processed.

Feel free to close this issue at any moment in time.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
