### ISSUE TITLE
503 Backend fetch failed

### ISSUE THREAD

**Issue by lmrodriguezr** [docmeta/rubydoc.info#124]
I'm getting the following error on several links on the site (`XID`s vary):

```
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 35743793

Varnish cache server
```

Some URLs throwing 503s include:

* http://www.rubydoc.info/github/bio-miga/miga/
* http://www.rubydoc.info/github
* http://www.rubydoc.info/find/github?q=montague

Thanks!
Miguel.

**Comment by lsegal** [comment]
Fixed. Thanks for reporting!

**Comment by limcross** [comment]
It is wrong again.

**Comment by paddor** [comment]
I've been experiencing this issue today.

**Comment by zapnap** [comment]
We're having some issues with our host today. Working on it.

**Comment by lsegal** [comment]
@paddor we should be back up now.

**Comment by paddor** [comment]
Thanks!

**Comment by paddor** [comment]
It's back again... https://www.rubydoc.info/gems/xmlrpc/0.3.0/XMLRPC/Client

**Comment by lsegal** [comment]
I see this working. Could it have been a small temporal issue?

**Comment by paddor** [comment]
I guess so. Now it’s working here too. But it does seem shaky. Is it an issue with Varnish?
