### ISSUE TITLE
Gemfile has incorrect/missing version specifiers

### ISSUE THREAD

**Issue by mvastola** [docmeta/rubydoc.info#126]
The `Gemfile` in this repo lacks version specifiers, and this is causing the app to fail if `bundle update` is run.

In particular, I am getting this error when starting the app:
```
regular expression should not contain ^: "^\\/github(?:\\/~([a-z])?|\\/)?$" (Mustermann::CompileError)
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/regular.rb:41:in `check_anchors'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/regular.rb:32:in `compile'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/regexp_based.rb:19:in `initialize'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/regular.rb:26:in `initialize'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `new'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `block in new'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/equality_map.rb:43:in `fetch'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `new'
  /usr/local/rvm/gems/ruby-2.5.1/gems/mustermann-1.0.3/lib/mustermann.rb:67:in `new'
  /usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1641:in `compile'
  /usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1629:in `compile!'
  /usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1604:in `route'
  /usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1386:in `get'
  /var/www-rubydoc/app.rb:331:in `<class:DocServer>'
  /var/www-rubydoc/app.rb:37:in `<top (required)>'
  config.ru:2:in `require'
  config.ru:2:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
```

This appears to be an issue with the `2.x.y` series of `sinatra`, which have a dependency on `mustermann (~> 1.0)`. The `Gemfile.lock` in `master` uses version `1.4.3`, but the version specifier in the `Gemfile` is simply `>= 1.3`. Switching it to `~> 1.3` resolves that issue. (I don't know enough about `mustermann` to be confident in editing `app.rb` to simply remove the offending lines, but that would probably be the better move, tbh.)

Additionally, running `rake -T` following `bundle update` gives the error:
```
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00005561de9731b0>
/usr/local/rvm/gems/ruby-2.5.1/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:101:in `define'
/usr/local/rvm/gems/ruby-2.5.1/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:78:in `initialize'
/var/www-rubydoc/Rakefile:5:in `new'
/var/www-rubydoc/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

This appears to be due to the fact the version of `rake` is unconstrained in the `Gemfile` and, as of version `11.0.1`, `rake` lacks the `last_comment` method, which is used by `rspec-core` until version`3.4.4`. (`rspec` is constrained to `~> 3.0.0` in `Gemfile`). This can be fixed by changing the `rspec` version constraint to `~> 3.x`.

**Comment by mvastola** [comment]
Also, I note that ff9cc32 updated `Gemfile.lock` two months ago, but it doesn't look like that was the result of a full `bundle update`.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.

As a sidenote, we are actively developing off of the `docker` branch for a little bit in order to create a Docker friendly version of the app. Technically master should still work but you may have better luck or even just an easier time working off of the docker branch.

**Comment by mvastola** [comment]
Yeah, this is working on `master` now. (Now if only I could remember what this issue was blocking me from doing. :-p)
