### ISSUE TITLE
Docs become stale after rewriting history on master

### ISSUE THREAD

**Issue by jlnr** [docmeta/rubydoc.info#130]
I had pushed a bad commit to one of my repositories a while ago, and quickly hot-fixed this by force-pushing the correct commit to the master branch. (Not generally a great idea, but it's mostly just me working on the repo.)

Ever since then, my rubydoc.info docs were stuck. rubydoc.info presumably updated my repo to the bad commit, and then `git pull --force` stopped working ([called from here](https://github.com/docmeta/rubydoc.info/blob/532015c19d485a5532eae9811ddb9640779b0920/lib/scm_checkout.rb#L138) to update checkouts). I've verified locally that `git pull --force` does indeed fail when the remote has been force-pushed:

```
$ git pull --force
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
From ../git-test
 + 324b10b...b744d70 master     -> origin/master  (forced update)
Auto-merging bar
CONFLICT (add/add): Merge conflict in bar
Automatic merge failed; fix conflicts and then commit the result.
```

I assume the fix is as simple as using a more resilient command than `git pull --force`. However, I don't have time to dig into this right now.

In case anyone finds this via Google — the quick workaround here is to use the "Add Project" dialog on the rubydoc.info front page, passing the commit hash of the current master HEAD.

**Comment by lsegal** [comment]
Fixed this manually. If you want to put together a patch to resolve this type of thing automatically that would be great!

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
