### ISSUE TITLE
Not able to access doc since it is not on the list but it is on rubygems

### ISSUE THREAD

**Issue by MarioRuiz** [docmeta/rubydoc.info#131]
Cannot access doc, it says not found: https://www.rubydoc.info/gems/nice_http/1.0.1

**Comment by MarioRuiz** [comment]
neither https://www.rubydoc.info/gems/nice_hash/1.7.0

**Comment by zapnap** [comment]
Should be working now -- thanks for reporting!

**Comment by MarioRuiz** [comment]
I just published a new gem... and same problem for https://www.rubydoc.info/gems/string_pattern/1.6.0

**Comment by zapnap** [comment]
@MarioRuiz docs for newly added gem versions are updated daily, so if you just pushed a version (and it looks like you did), it might take up to 24h to appear.

**Comment by MarioRuiz** [comment]
This is something new then, until a month ago docs were available in the moment they were posted on rubygems

**Comment by zapnap** [comment]
Oh we do have a hook that's right. -derp- I'll have to look into why it's not firing this wkend.

**Comment by zapnap** [comment]
Btw - I think the core issue here has been fixed (had to do with changed versions detection logic). Thanks again for reporting.
