### ISSUE TITLE
Incorrect github post-receive hook link

### ISSUE THREAD

**Issue by bolshakov** [docmeta/rubydoc.info#132]
> Looking for a GitHub post-receive hook? Use http://www.rubydoc.info/checkout.

But it should have `https` schema

**Comment by zapnap** [comment]
Want to send a quickie PR for that? Be happy to accept it :)

**Comment by bolshakov** [comment]
I’m happy to s nd PR, but this url is in settings, which is not in repo

**Comment by zapnap** [comment]
D'oh! Glad one of us is paying attention :) Will fix

**Comment by zapnap** [comment]
Fixed. Thanks for reporting.
