### ISSUE TITLE
Links In search require JavaScript

### ISSUE THREAD

**Issue by jalcine** [docmeta/rubydoc.info#133]
I conventionally keep JavaScript off for performance reasons (the Web is so much faster) but stumbled upon an interesting bug on rubydoc.info. It looks like anchor-based links are used to navigate to docs when the full URI could be used.

Steps to Reproduce:
- Use a extension like [`NoScript`](https://noscript.net/) to block JavaScript.
- Navigate to https://www.rubydoc.info/gems.
- Click on any gem listing.

Expected behavior:
- Upon clicking the link, the browser navigates to the gem's documentation.

Actual behavior:
- The anchor for the page gets updated to an invalid location on the page. User behavior results in a no-op.

**Comment by lsegal** [comment]
This is unfortunately a feature to avoid webcrawlers from unwittingly triggering RubyDoc's on-demand documentation generation for all gems in our index while still also allowing them to crawl generated documentation. 

If you have ideas on how else this can be done, we could accept a PR to address this.

**Comment by GRardB** [comment]
Would adding a [`rel="nofollow"`](https://support.google.com/webmasters/answer/96569?hl=en) to the links work?

**Comment by lsegal** [comment]
We can't rely on `rel="nofollow"` (or robots.txt) for a few reasons: 

1. Not all of our crawlers are Google or follow Google's crawling standards. We really can't afford to have our entire index triggered by a crawler that chooses not to respect that attribute, and we'd rather not have to ban a slew of hosts retroactively. In looking into this it's unclear which crawlers other than Google may or may not follow the link. Note that this code was initially added in response to such crawlers, quite a while ago.

2. This can, in some ways, affect Google's SEO for docs generated on the site:

> In general, we don’t follow them. This means that Google does not transfer PageRank or anchor text across these links. Essentially, using nofollow  causes us to drop the target links from our overall graph of the web.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
