### ISSUE TITLE
503 errors when browsing documentation

### ISSUE THREAD

**Issue by dzunk** [docmeta/rubydoc.info#147]
For the past several days, I've been receiving 503 errors and glitched out pages when attempting to browse documentation.

This doesn't appear limited to a particular gem, and is happening on multiple devices (both desktop and mobile) so I don't believe it's a client issue.

----
![image](https://user-images.githubusercontent.com/16783036/87883350-a571fe00-c9bb-11ea-8c4e-b0b7b97beff9.png)
----
![image](https://user-images.githubusercontent.com/16783036/87883362-af93fc80-c9bb-11ea-8b5b-3d50def15024.png)
----
![image](https://user-images.githubusercontent.com/16783036/87883365-b6bb0a80-c9bb-11ea-8ef7-84c53f0474dc.png)

**Comment by dzunk** [comment]
Cloudflare agrees there's an issue 😂 Sorry if this isn't the right place to report site downtime, I couldn't find a better one and the issues here look fairly active
<img width="974" alt="Screen Shot 2020-07-19 at 12 36 55 PM" src="https://user-images.githubusercontent.com/16783036/87883490-93448f80-c9bc-11ea-9361-de44b7d4b4a5.png">

**Comment by lsegal** [comment]
Hi there,

We were in progress of a fix, which should be completed now. Thanks for reporting!

**Comment by dzunk** [comment]
Thanks @lsegal, everything seems to be working now!

**Comment by dezka** [comment]
@lsegal this problem seems to be back, myself and multiple people I work with remotely are seeing the same thing that was originally reported here.

**Comment by javierav** [comment]
Same problem now!

```
Error 503 Service Unavailable
Service Unavailable

Guru Meditation:
XID: 67031005

Varnish cache server
```

**Comment by deviant** [comment]
Getting the same issue here, could this issue be reopened?

**Comment by kenyon** [comment]
This has returned.
