### ISSUE TITLE
Oops, We Couldn't Find That Gem

### ISSUE THREAD

**Issue by cynicer** [docmeta/rubydoc.info#149]
Hello,

I'm trying to figure out why the documentation for our plugin (https://rubydoc.info/gems/fastlane-plugin-dynatrace) is not being generated/displayed on the website? As far as I've seen the gem should be parse hourly/daily, right? I tried running the yard server locally on the code and it picked up and parsed our README just fine.

https://rubydoc.info/find/gems?q=fastlane-plugin-dynatrace

Does anybody know how to solve this issue?

Thanks!

Regards,
Marcel

**Comment by cynicer** [comment]
Deploy with a higher version numbers solved the issue for me.

**Comment by shrik450** [comment]
Can you reopen this? This issue is affecting other gems, including popular ones such as [Pundit.](https://rubydoc.info/gems/pundit) The gem even shows up in the search, but it directs to the "Oops" page.

**Comment by ybiquitous** [comment]
Hi, I'm in trouble too... 😰 

On the [document page of RuboCop RSpec](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecalignleftletbrace), the link to `www.rubydoc.info` returns 404 "Oops":

https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/AlignLeftLetBrace

<img width="764" alt="image" src="https://user-images.githubusercontent.com/473530/104407637-6bb63480-55a5-11eb-9f35-d0053a2947ec.png">

**Comment by lsegal** [comment]
This should now be addressed, thanks for reporting.

**Comment by ybiquitous** [comment]
This problem seems fixed, right?

**Comment by cynicer** [comment]
Seems so.

**Comment by Fryguy** [comment]
Doesn't seem fixed (or perhaps it broke again)

- https://rubydoc.info/gems/rubocop
- https://rubydoc.info/gems/nokogiri
