### ISSUE TITLE
Issue with production: SQLite3::CorruptException: database disk image is malformed

### ISSUE THREAD

**Issue by rtlong** [docmeta/rubydoc.info#152]
I'm seeing this error page intermittently when browsing rubydoc.info. Feels like when a page isn't fully cached I'm running into this, but the site is still mostly working.

![image](https://user-images.githubusercontent.com/199912/108872851-3ba87b00-75c0-11eb-8108-940f35beda65.png)

**Comment by lsegal** [comment]
This should now be resolved. Thank you for reporting!

**Comment by AlexWayfer** [comment]
Again.

![2021-09-06_14-49](https://user-images.githubusercontent.com/6510020/132213154-94c99ccf-239b-48bf-bcb2-0d255b9e211b.png)

**Comment by lsegal** [comment]
Is it possible this was just a temporal issue? Not seeing this anymore.

**Comment by AlexWayfer** [comment]
> Is it possible this was just a temporal issue? Not seeing this anymore.

Yep, maybe. But I got a few yesterday in different places (different gems). We should monitor such errors, I think.

**Comment by dmarcoux** [comment]
I'm also getting this from time to time while browsing [Octokit](https://www.rubydoc.info/gems/octokit) and [Gitlab](https://www.rubydoc.info/gems/gitlab)

**Comment by AlexWayfer** [comment]
Another case on https://www.rubydoc.info/gems/slack-notifier/Slack/Notifier/APIError

![2021-09-17_12-20](https://user-images.githubusercontent.com/6510020/133759309-a3b8e31c-bcf0-4537-ab86-60057b3cc2b6.png)

**Comment by son1112** [comment]
Throwing my hat in the ring...

<img width="1209" alt="rubydocissue2" src="https://user-images.githubusercontent.com/760169/134717370-8f3347aa-b11c-41fa-8724-3ef247d8e4de.png">

**Comment by AlexWayfer** [comment]
![image](https://user-images.githubusercontent.com/6510020/135928486-2c79bdca-7f07-49aa-a2b1-a428b65b06d4.png)
