### ISSUE TITLE
a lot of the gems aren't returning any info

### ISSUE THREAD

**Issue by d-m-u** [docmeta/rubydoc.info#155]
https://www.rubydoc.info/gems/factory_bot and most of the others I looked at are currently not found:

<img width="644" alt="Screen Shot 2021-04-02 at 8 59 33 AM" src="https://user-images.githubusercontent.com/16326669/113417607-bfa90c00-9391-11eb-954c-06060ce3b566.png">

**Comment by NARKOZ** [comment]
Same for a gitlab gem as seen in https://github.com/NARKOZ/gitlab/issues/589

**Comment by lsegal** [comment]
Sorry for the delay but this should now be resolved.

**Comment by d-m-u** [comment]
thanks!

**Comment by mvz** [comment]
@lsegal I'm seeing this problem again, in this case with aruba: http://www.rubydoc.info/gems/aruba

**Comment by lsegal** [comment]
Thanks for the report, I just did a reset and it seems to be working.

**Comment by mvz** [comment]
Thanks, @lsegal!
