### ISSUE TITLE
Unable to open rubyzip documentation

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [docmeta/rubydoc.info#161]
https://www.rubydoc.info/gems/rubyzip

Returns "Oops, We Couldn't Find That Gem" error, but I did visit the gem's page just a day ago.

Looks like a regular ocurrence for some gems/similar to https://github.com/docmeta/rubydoc.info/issues/155

---

As a workaround, browsing GitHub-linked documentation still works - https://www.rubydoc.info/github/rubyzip/rubyzip

**Comment by lsegal** [comment]
Thanks for reporting. We actually discovered an issue with sqlite and fixed via 1b679aaaafe358470de8982817281365882bb4f4 that should resolve this and #155.
