### ISSUE TITLE
Support for custom templates

### ISSUE THREAD

**Issue by 0x1eef** [docmeta/rubydoc.info#169]
I have created a simple custom template that adds my own stylesheet. It works locally, but not on rubydoc.info. 
Should it work, and if not - can support be added?

**Comment by skatkov** [comment]
Can you maybe share, in PR, what you've built so far?

**Comment by 0x1eef** [comment]
I have made a few edits to the default template, and for now I'm carrying them around in each of my projects and hosting the contents on GitHub pages - since rubydoc.info is not including them.

Example is here:
https://github.com/0x1eef/trip.rb/tree/main/.yardoc-template/default

**Comment by 0x1eef** [comment]
I just realized some of those edits involve executing Ruby code so it is probably not practical to execute them on rubydoc.info.

**Comment by 0x1eef** [comment]
Hey :wave: I'm cleaning up my issue list. Going to close this one due to inactivity.
