### ISSUE TITLE
Bug with updating documentation

### ISSUE THREAD

**Issue by tenderlove** [docmeta/rubydoc.info#19]
There seems to be a bug.  This screenshot should explain:

http://img.skitch.com/20100922-kcnks7jpb6m59245yaxys3ran4.jpg

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
