### ISSUE TITLE
Ajax method/class search should not fire when a non-printable character is pressed

### ISSUE THREAD

**Issue by mcmire** [docmeta/rubydoc.info#24]
When I am looking at a project's docs and I search for a method or class, if I click on the search box and simply press, for instance, arrow-left or arrow-right, an Ajax request is taking place, as evidenced by the spinner. It may seem petty, but it's actually one of those things that makes the UX smoother. I can take a look at this and send you a pull request.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
