### ISSUE TITLE
examples directory seems to be removed after checkout => embedding of example files doesn't work

### ISSUE THREAD

**Issue by michaelklishin** [docmeta/rubydoc.info#30]
This is a follow-up to lsegal/yard#341. I include files from examples directory in the repository root and it works fine locally but not on rubydoc.info.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
