### ISSUE TITLE
Permalink for methods ending with a question mark not working

### ISSUE THREAD

**Issue by bytesource** [docmeta/rubydoc.info#44]
Hi Loren, 

It seems that permalinks for methods ending with a question mark are not working. For example, clicking on the _permalink_ link  of the [is_boolean?](http://rubydoc.info/github/bytesource/with_validations/master/WithValidations#is_boolean%3F-instance_method) method returns a _404 not found_ error:
http://rubydoc.info/github/bytesource/with_validations/master/WithValidations:is_boolean%3F

Best regards,

Stefan

**Comment by jonathanhefner** [comment]
This appears to still be an issue, and it's not just limited to methods that end in a question mark.  Examples:
  - [permalink](http://www.rubydoc.info/gems/yard/YARD%2FDocstring%3A%252B) for [plus method](http://www.rubydoc.info/gems/yard/YARD/Docstring#%2B-instance_method)
  - [permalink](http://www.rubydoc.info/gems/yard/YARD%2FCodeObjects%2FProxy%3A%253C%253D%253E) for [spaceship method](http://www.rubydoc.info/gems/yard/YARD/CodeObjects/Proxy#%3C%3D%3E-instance_method)
  - [permalink](http://www.rubydoc.info/gems/yard/YARD%2FOptions%3A%255B%255D) for [square brackets](http://www.rubydoc.info/gems/yard/YARD/Options#%5B%5D-instance_method)
  - [permalink](http://www.rubydoc.info/gems/yard/YARD%2FHandlers%2FBase%3Aabort%2521) for [bang method](http://www.rubydoc.info/gems/yard/YARD/Handlers/Base#abort%21-instance_method)

It looks like there might be some double-escaping happening with permalink urls.

**Comment by lsegal** [comment]
It's not really double escaping so much as it is a discrepancy between urlencoding on the link generation side vs. the url decoding on the path routing side. It seems that the `request.path_info` data that YARD gets is not as aggressively decoded, so YARD is getting "%5B" in the path when it should be seeing a "[". Not sure why that is happening, but I've updated the way YARD urlencodes which should provide nicer URLs and fix this problem.
