### ISSUE TITLE
rspec docs have not updated

### ISSUE THREAD

**Issue by dchelimsky** [docmeta/rubydoc.info#56]
I released rspec-core, rspec-expectations, rspec-mocks and rspec-rails v2.12.0 last night at 10:30 CT and have yet to update.
- http://rubydoc.info/gems/rspec-core/
- http://rubydoc.info/gems/rspec-expectations/
- http://rubydoc.info/gems/rspec-mocks/
- http://rubydoc.info/gems/rspec-rails/

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
