### ISSUE TITLE
Yardoc doesn't update html after refresh

### ISSUE THREAD

**Issue by flyinprogrammer** [docmeta/rubydoc.info#59]
follow the instructions in the readme, instead of "rackup config.ru" run "unicorn"

Add a repo to the application
View that it generates the correct html with first add.
Now go to the repo, and modify your documentation
Go back to the app, and click the refresh button
The yard documentation will not update however/and:

Edits to readme files are reflected correctly
Time stamps at the bottom of the html files are updated [it's not the webserver cacheing]
Opening irb in repo/github/user/project/master and inspecting the registry shows the updates
Restarting the webservice will cause the showing of new yardoc 
Using WEBbrick this problem doesn't exist.

I was able to reproduce this on cent os and debian, with and without the use of rvm. here is my gem set:

Installing rake (10.0.3)
Installing RedCloth (4.2.9) with native extensions
Installing i18n (0.6.1)
Installing multi_json (1.5.0)
Installing activesupport (3.2.10)
Installing builder (3.1.4)
Installing connection_pool (0.9.3)
Installing rubinius-core-api (0.0.1)
Installing rubinius-actor (0.0.2)
Installing girl_friday (0.11.1)
Installing airbrake (3.1.6)
Installing bluecloth (2.2.0) with native extensions
Installing diff-lcs (1.1.3)
Installing github-markup (0.7.5)
Installing json (1.7.6) with native extensions
Installing kgio (2.7.4) with native extensions
Installing kramdown (0.14.1)
Installing syntax (1.0.0)
Installing maruku (0.6.1)
Installing rack (1.4.1)
Installing rack-protection (1.3.2)
Installing raindrops (0.10.0) with native extensions
Installing rdiscount (1.6.8) with native extensions
Installing redcarpet (1.17.2) with native extensions
Installing rspec-core (2.12.2)
Installing rspec-expectations (2.12.1)
Installing rspec-mocks (2.12.1)
Installing rspec (2.12.0)
Installing sequel (3.42.0)
Installing tilt (1.3.3)
Installing sinatra (1.3.3)
Installing sqlite3 (1.3.6) with native extensions
Installing unicorn (4.5.0) with native extensions
Using yard (0.8.3) from source at ../yard
Installing yard-kramdown (0.0.1)
Installing yard-rails (0.3.0)
Installing yard-sd (0.0.2)
Using bundler (1.2.3)

$ ruby --version
ruby 1.9.3p327 (2012-11-10) [x86_64-darwin12.2.0]

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
