### ISSUE TITLE
Documentation Badge

### ISSUE THREAD

**Issue by trans** [docmeta/rubydoc.info#61]
Not very good, but it's a start:

![yarddoc](https://f.cloud.github.com/assets/23423/241231/303578dc-899b-11e2-84e7-50387dcc3abe.png)

Mr. Honnef's idea about a dynamic image with percentage of completeness is a interesting idea. I was looking around for tools that would make this easy to do. So far chunky_png looks the most promising. What do you think? Should we round everything to the nearest 5% and just have 20 static images. Or, given how small they are I suppose 100 static images wouldn't be such a big deal?

**Comment by lsegal** [comment]
Closing this out since there are some pretty good generalized solutions to do this out there today!
