### ISSUE TITLE
Issues with rspec projects (github) on rubydoc.info

### ISSUE THREAD

**Issue by myronmarston** [docmeta/rubydoc.info#80]
I'm working on a blog post announcing what's new in RSpec 3 and have links to docs on rubydoc.info.  I'm using github links because the gem docs won't show up until 3.0 final is released.  rspec-core is now 404ing:

http://rubydoc.info/github/rspec/rspec-core

It worked fine last night, though.  rspec-expectations and rspec-rails are working fine:

http://rubydoc.info/github/rspec/rspec-expectations
http://rubydoc.info/github/rspec/rspec-rails

...but rspec-mocks is not rendering the README:

http://rubydoc.info/github/rspec/rspec-mocks

Any idea want went wrong with rspec-core and rspec-mocks?

Thanks!

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
