### ISSUE TITLE
Rubydoc.info implementation using private gem server

### ISSUE THREAD

**Issue by HoneyryderChuck** [docmeta/rubydoc.info#81]
Sorry for using the issues section, but I didn't find the discussion forum for this gem. 

We have an internal private gem server for the in-house gems, and we would like to use rubydoc.info as the documentation server. The standard implementation pushes information from rubygems and github, but we would like to shut them down. We would also like to list the documentation of the inhouse gems (by, maybe, providing the address of the gem server) and (the best possible case) somehow support some post hook that would rebuild/version the documentation. 

Does Rubydoc support this current set of features? Or is there something like this?

Thx for the reply in advance
Tiago

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. Just as an FYI, RubyDoc.info now has a configuration to specify a custom gem server which should allow you to use private mirrors.

https://github.com/docmeta/rubydoc.info/blob/master/config/config.yaml.sample#L65
