### ISSUE TITLE
'View Source' links to Github not working on many repos

### ISSUE THREAD

**Issue by tinco** [docmeta/rubydoc.info#91]
Hi,

I'm not sure if this is a known problem or perhaps someone elses problem, for a while I've noticed many view source on github urls to be broken. An example of a page that has broken links is this one:

http://www.rubydoc.info/github/carlhuda/bundler/Bundler/GemHelper

There are many more.

Is this the right place to report this? Is this a problem with Rubydoc.info, or are these docs out of date and should I file an issue with the creator of the github project?

**Comment by jirutka** [comment]
I have the same problem with my projects.

**Comment by lsegal** [comment]
GitHub links only work when the branch name is part of the URL. This is something we could fix by inferring `master`, but it would never be 100% reliable. The easy fix is to ensure you're browsing from the rubydoc generated URLs, which always include the branch name / ref you're viewing:

http://www.rubydoc.info/github/carlhuda/bundler/master

**Comment by jirutka** [comment]
Thanks for your advice, it works! However, this should be written in some FAQ…

**Comment by TheLonelyGhost** [comment]
@lsegal Going from the search section of rubydoc.info into the docs for a particular repository actually end up on the page without the ref.

http://www.rubydoc.info/find/github?q=mongoid

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.

**Comment by heynan0** [comment]
I was looking at the documentation for capybara and ran into this issue. The links to view source on GitHub do not work. They use "Capybara" instead of the branch name "master" (replacing that in the redirected url fixes it).

> [...] The easy fix is to ensure you're browsing from the rubydoc generated URLs [...]

@lsegal, How can one go about doing that through the web interface without having to manually type in the branch name? It seems that the interface already knows about the branch yet redirects without its name. See example screenshot with oval highlight:

![Screen Shot 2020-06-30 at 5 46 40 PM](https://user-images.githubusercontent.com/58703271/86190868-68bc9080-bafa-11ea-9faa-9e6260cfff62.png)

**Comment by lsegal** [comment]
@heynan0 you're right, this is something that _can_ be fixed if the layout template made the current active library version available to the rest of the JS scripts running on the page. It was something I was about to pick up a few weeks ago actually but it fell off my plate.

The process would be roughly:

1. Override the breadcrumb.erb template in layout ([this](https://github.com/docmeta/rubydoc.info/tree/main/templates/default/layout/html) is the directory but you would need to add the appropriate breadcrumb.erb files [documented here](https://www.rubydoc.info/gems/yard/file/docs/Templates.md#creating-a-template))
2. Set some variable on window that contains the library version. You can look at [YARD's own breadcrumb template](https://github.com/lsegal/yard/blob/main/lib/yard/server/templates/default/layout/html/breadcrumb.erb#L24) when you override to see where it's coming from and just put that into a variable.
3. Jump into https://github.com/docmeta/rubydoc.info/blob/main/templates/default/fulldoc/html/js/rubydoc_custom.js and use that variable.

Overall not that difficult but haven't had a chance to sit down and solve this.

**Comment by lsegal** [comment]
Ok yes VERY easy indeed ^

**Comment by lsegal** [comment]
This is live now btw.

**Comment by heynan0** [comment]
@lsegal it works fine now. Thank you very much for fixing it! :)

**Comment by tinco** [comment]
Thank you!
