### ISSUE TITLE
add yard-activesupport-concern please :)

### ISSUE THREAD

**Issue by s12chung** [docmeta/rubydoc.info#97]
https://github.com/digitalcuisine/yard-activesupport-concern

simple plugin.

**Comment by lsegal** [comment]
I'm not opposed to this. It seems to be a simple plugin. I wonder if it might be better to create generalized support for parsing inner blocks of things through a simple directive like:

```ruby
# @!parseblock [class|instance] OPTIONAL_NAMESPACE
dsl_method do
  ...
end
```

For example,

```ruby
module M
  extend ActiveSupport::Concern

  # @!parseblock [instance]
  included do
    # @!method disabled
    # @!scope class
    # @return [Collection<Model>] Return a scope to get all disabled records
    scope :disabled, -> { where(disabled: true) }
  end

  # @!parseblock [class]
  class_methods do
    # A quick way to get all published records
    # @return [Collection<Model>] Return a scope to get all published records
    def published
      where(published: true)
    end
  end
end
```

At that point you could attach macros to `included` and `class_methods` to do it automatically. This would work without requiring plugins.

**Comment by s12chung** [comment]
@lsegal i think your solution is better. i'm not too familiar with the yard api to do a PR though. how long do you think it'll take to implement?

**Comment by lsegal** [comment]
@s12chung this is not something I would have time to implement right now, but this would be something you could open a PR for on [lsegal/yard](http://github.com/lsegal/yard) if you were interested. 

You can look at http://www.rubydoc.info/gems/yard/YARD/Tags/Directive for documentation on creating a directive, and look at source for other similar directives for guidance (https://github.com/lsegal/yard/blob/master/lib/yard/tags/directives.rb).

**Comment by s12chung** [comment]
hmm... i'll see if i can find some time to do it. thanks for the direction, i think it'll help a lot.

**Comment by olance** [comment]
That would be a nice generic way to do it indeed :)

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.

As a sidenote, RubyDoc.info now supports running plugins or extensions for projects during the parsing phase without the need for whitelisting so you should be able to run this plugin assuming it does not modify templates.
